// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrG5Onhez0hU0zU49stVcP5FCz_4CHXr0',
    appId: '1:944935560712:web:2b98de70fb3b41fa6153bd',
    messagingSenderId: '944935560712',
    projectId: 'app-gnuhtalktalk',
    authDomain: 'app-gnuhtalktalk.firebaseapp.com',
    storageBucket: 'app-gnuhtalktalk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz8HziyMWGCrN1hvnrJlxPbXzOgYHhwh0',
    appId: '1:944935560712:android:a308aef4c991bc7c6153bd',
    messagingSenderId: '944935560712',
    projectId: 'app-gnuhtalktalk',
    storageBucket: 'app-gnuhtalktalk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVB2TDfr2-145wbueh7Y9Jhi4P2nBxf30',
    appId: '1:944935560712:ios:3d7a27ebc205db196153bd',
    messagingSenderId: '944935560712',
    projectId: 'app-gnuhtalktalk',
    storageBucket: 'app-gnuhtalktalk.firebasestorage.app',
    iosBundleId: 'com.example.gnuhtalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVB2TDfr2-145wbueh7Y9Jhi4P2nBxf30',
    appId: '1:944935560712:ios:3d7a27ebc205db196153bd',
    messagingSenderId: '944935560712',
    projectId: 'app-gnuhtalktalk',
    storageBucket: 'app-gnuhtalktalk.firebasestorage.app',
    iosBundleId: 'com.example.gnuhtalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrG5Onhez0hU0zU49stVcP5FCz_4CHXr0',
    appId: '1:944935560712:web:bc830b6725883c076153bd',
    messagingSenderId: '944935560712',
    projectId: 'app-gnuhtalktalk',
    authDomain: 'app-gnuhtalktalk.firebaseapp.com',
    storageBucket: 'app-gnuhtalktalk.firebasestorage.app',
  );
}
